Algoritmo "area_circulo"
// Disciplina   : [Lógica de Programação]
// Professor   : Jailson Costa dos Santos 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Eduardo Barbosa Silva
// Data atual  : 26/09/2025
Var
// Seção de Declarações das variáveis
area,raio:real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
escreval("Digite o raio do circulo")
leia(raio)
area <- (raio*raio)*pi
escreval("Resultado: ", area)

Fimalgoritmo