Algoritmo "semnome"
// Disciplina   : [Lógica de Programação]
// Professor   : Jailson Costa dos Santos
// Descrição   : Revelador de número antecessor
// Autor(a)    : Eduardo Barbosa Silva
// Data atual  : 29/08/2025
var
x,y,z:inteiro



inicio
escreval("Digite quantas vezes gostaria de rodar o programa")
leia(y)
para x de 0 ate y passo 1 faca
escreval("Digite um valor, e seu antecessor será revelado")
leia(z)
z <- z - 1
escreval(z)
fimpara



fimalgoritmo