Algoritmo "subtracao"
// Disciplina   : [Lógica de Programação]
// Professor   : Jailson Costa dos Santos
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Eduardo Barbosa Silva
// Data atual  : 26/09/2025
Var
// Seção de Declarações das variáveis
num1,num2:real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
escreval("Digite dois valores para subtrair")
leia(num1,num2)
escreval("Resultado: ",num1-num2)

Fimalgoritmo